modLoader="javafml"
loaderVersion="[36,)"
license="Copyright 2021 Milkeyyy"

[[mods]]
modId="myposition"
version="1.0.0"
displayName="MyPosition"
credits="Created by Milkeyyy using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="Milkeyyy"

[[dependencies.myposition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




