modLoader="javafml"
loaderVersion="[36,)"
license="Copyright 2021 Milkeyyy"

[[mods]]
modId="myposition"
version="1.0.0-release"
displayName="MyPosition"
credits="Created by Milkeyyy using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Milkeyyy/MyPositionMod"
updateJSONURL="https://raw.githubusercontent.com/Milkeyyy/MyPositionMod/master/update.json"
authors="Milkeyyy"
description='''
I'm here.
'''

[[dependencies.myposition]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




